---
DynamixelHardware:
  ros__parameters:
    number_of_joints: 2
    joint_ids: [22, 24]
    joint_names: [LHand, LGripper]
    serial_port: /dev/ttyACM0
    baud_rate: 1000000
    dxl_protocol_version: 2.0
    use_dummy: false
