dynamixel_hardware:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baud_rate: 1000000
    joint_ids:
      left_hip_yaw: 1
      left_hip_roll: 2
      left_hip_pitch: 3
      left_knee: 4
      left_ankle_pitch: 5
      left_ankle_roll: 6
