dynamixel_hardware:
  ros__parameters:
    use_dummy: false
    serial_port: /dev/ttyUSB0
    baud_rate: 57600
    dxl_protocol_version: 2.0
    joints:
      - id: 1
        name: head_pan
        model: MX-28
      - id: 2
        name: head_tilt
        model: MX-28

