controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: false

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters: {}

head_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - HeadYaw
      - HeadPitch
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

left_arm_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

right_arm_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

left_hand_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - LWrist
      - LGrip
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

right_hand_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - RWrist
      - RGrip
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

left_leg_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true

right_leg_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: true
