controller_manager:
  ros__parameters:
    right_leg_controller:
      command_interfaces:
      - position
      joints:
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle_pitch
      - right_ankle_roll
      state_interfaces:
      - position
      - velocity
      type: joint_trajectory_controller/JointTrajectoryController
