# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - hros5_controller

  hros5_controller:
    type: FollowJointTrajectory
    default: true
    action_ns: follow_joint_trajectory
    joints:
      - HeadYaw
      - HeadPitch
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
      - LWrist
      - LGrip
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
      - RWrist
      - RGrip
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
