joints:
  - name: RShoulderPitch
    id: 1
    cw_limit: 0
    ccw_limit: 4095
    offset_deg: 0.0
  - name: RShoulderRoll
    id: 3
    cw_limit: 0
    ccw_limit: 3672
    offset_deg: 0.0
  - name: RElbowPitch
    id: 5
    cw_limit: 896
    ccw_limit: 3712
    offset_deg: 0.0
  - name: RWrist
    id: 23
    cw_limit: 548
    ccw_limit: 3548
    offset_deg: 0.0
  - name: RGrip
    id: 21
    cw_limit: 1640
    ccw_limit: 2800
    offset_deg: 0.0
