controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_position_controller:
      type: position_controllers/JointPositionController
      joint: joint1

dynamixel_hardware:
  ros__parameters:
    use_dummy: false
    serial_port: "/dev/ttyUSB0"
    baudrate: 1000000
    joints:
      - id: 1
        name: joint1
        model: "MX-28"
