/**:
  ros__parameters:
    config_package: hros5_control
    bus_config: config/dxl_bus.yaml
    config_file: config/joints/head.yaml
    command_topic: /hros5/head/target_angles_deg
    max_step_deg: 2.0
