/**:
  ros__parameters:
    config_package: hros5_control
    bus_config: config/dxl_bus.yaml
    config_file: config/joints/left_arm.yaml
    command_topic: /hros5/left_arm/target_angles_deg
    max_step_deg: 2.0
    grip_max_step_deg: 3.0
