#!/usr/bin/env python3
"""
dxl_apply_limits_p2.py

Apply previously captured MX-series limits onto servos running Protocol 2.0
firmware. The script expects a CSV generated by dxl_read_limits.py --all
(default: mx_limits_all.csv) and writes the stored CW/CCW position limits
back to each reachable servo.

Usage:
  python3 dxl_apply_limits_p2.py --csv mx_limits_all.csv --port /dev/dxl --baud 1000000
  python3 dxl_apply_limits_p2.py --ids 1 3 5 --dry-run
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List

from dynamixel_sdk import (
    PortHandler,
    PacketHandler,
    COMM_SUCCESS,
)

# --- Protocol 2.0 addresses (MX-28/64/106 2.0 control table) ---
ADDR_MIN_POS = 52          # 4 bytes (CW limit / min position)
ADDR_MAX_POS = 48          # 4 bytes (CCW limit / max position)


CSV_REQUIRED_FIELDS = [
    "id",
    "cw_limit_ticks",
    "ccw_limit_ticks",
]


def read_csv_limits(csv_path: Path) -> Dict[int, Dict[str, str]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    with csv_path.open() as csv_file:
        reader = csv.DictReader(csv_file)
        missing = [field for field in CSV_REQUIRED_FIELDS if field not in reader.fieldnames]
        if missing:
            raise ValueError(
                f"CSV is missing required columns: {', '.join(missing)}. "
                "Re-run mx_read_limits.py --all to regenerate."
            )
        rows: Dict[int, Dict[str, str]] = {}
        for row in reader:
            try:
                dxl_id = int(row["id"])
            except (ValueError, KeyError):
                continue
            rows[dxl_id] = row
        return rows


def assert_comm(result: int, error: int, packet: PacketHandler, context: str) -> None:
    if result != COMM_SUCCESS:
        raise RuntimeError(f"{context}: COMM error {packet.getTxRxResult(result)}")
    if error != 0:
        raise RuntimeError(f"{context}: DXL error {packet.getRxPacketError(error)}")


def write_dword(packet: PacketHandler, port: PortHandler, dxl_id: int, addr: int, value: int, label: str) -> None:
    result, error = packet.write4ByteTxRx(port, dxl_id, addr, value)
    assert_comm(result, error, packet, f"{label} (addr {addr})")


def apply_limits_to_servo(
    packet: PacketHandler,
    port: PortHandler,
    dxl_id: int,
    row: Dict[str, str],
    dry_run: bool = False,
) -> None:
    cw_ticks = int(float(row["cw_limit_ticks"]))
    ccw_ticks = int(float(row["ccw_limit_ticks"]))

    actions = [
        ("CW limit", write_dword, ADDR_MIN_POS, cw_ticks),
        ("CCW limit", write_dword, ADDR_MAX_POS, ccw_ticks),
    ]

    for label, writer, addr, value in actions:
        if dry_run:
            print(f"[ID {dxl_id}] DRY RUN -> {label}: {value}")
            continue
        writer(packet, port, dxl_id, addr, value, label)
        print(f"[ID {dxl_id}] Set {label} to {value}")


def main():
    parser = argparse.ArgumentParser(
        description="Apply saved MX servo limits (Protocol 2.0)."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("mx_limits_all.csv"),
        help="CSV file generated by dxl_read_limits.py --all",
    )
    parser.add_argument(
        "--port",
        type=str,
        default="/dev/dxl",
        help="Serial port for the Dynamixel bus (default: /dev/dxl)",
    )
    parser.add_argument(
        "--baud",
        type=int,
        default=1000000,
        help="Baudrate (default: 1000000)",
    )
    parser.add_argument(
        "--ids",
        nargs="+",
        type=int,
        default=None,
        help="Optional subset of IDs to update. Defaults to all IDs listed in the CSV.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended writes without sending them to the servos.",
    )
    args = parser.parse_args()

    try:
        limits_map = read_csv_limits(args.csv)
    except Exception as exc:
        print(f"❌ Failed to read CSV: {exc}", file=sys.stderr)
        sys.exit(1)

    if not limits_map:
        print("❌ CSV contains no servo entries.", file=sys.stderr)
        sys.exit(1)

    target_ids: List[int] = args.ids if args.ids else sorted(limits_map.keys())
    missing_ids = [dxl_id for dxl_id in target_ids if dxl_id not in limits_map]
    if missing_ids:
        print(
            f"⚠ CSV does not contain data for IDs: {missing_ids}. "
            "They will be skipped.",
            file=sys.stderr,
        )
        target_ids = [dxl_id for dxl_id in target_ids if dxl_id in limits_map]

    if not target_ids:
        print("❌ No valid IDs to process.", file=sys.stderr)
        sys.exit(1)

    port = PortHandler(args.port)
    if not port.openPort():
        print(f"❌ Failed to open port {args.port}", file=sys.stderr)
        sys.exit(1)
    if not port.setBaudRate(args.baud):
        print(f"❌ Failed to set baudrate to {args.baud}", file=sys.stderr)
        sys.exit(1)

    packet = PacketHandler(2.0)

    print("=== Applying Protocol 2.0 Limits ===")
    print(f"Port  : {args.port}")
    print(f"Baud  : {args.baud}")
    print(f"CSV   : {args.csv}")
    print(f"IDs   : {target_ids}")
    print(f"Dry-run: {args.dry_run}")
    print("")

    processed = 0
    for dxl_id in target_ids:
        row = limits_map[dxl_id]
        try:
            apply_limits_to_servo(packet, port, dxl_id, row, dry_run=args.dry_run)
            processed += 1
        except Exception as exc:
            print(f"[ID {dxl_id}] ❌ Failed to apply limits: {exc}")

    port.closePort()
    print(f"\n✅ Completed. Limits {'planned for' if args.dry_run else 'applied to'} {processed} servo(s).")


if __name__ == "__main__":
    main()
