#!/usr/bin/env python3
"""Generate per-limb joint YAMLs from the canonical Dynamixel config."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


DEFAULT_INPUT = Path("src/hros5_control/config/hros5_dynamixel_joints_with_limits.yaml")
DEFAULT_OUTPUT_DIR = Path("src/hros5_control/config/joints")


class _IndentedDumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow=flow, indentless=False)


JOINT_GROUPS: dict[str, list[str]] = {
    "head": ["HeadYaw", "HeadPitch"],
    "left_arm": ["LShoulderPitch", "LShoulderRoll", "LElbowPitch", "LWrist", "LGrip"],
    "right_arm": ["RShoulderPitch", "RShoulderRoll", "RElbowPitch", "RWrist", "RGrip"],
    "hands": ["LGrip", "LWrist", "RGrip", "RWrist"],
    "left_leg": [
        "LHipYaw",
        "LHipRoll",
        "LHipPitch",
        "LKneePitch",
        "LAnklePitch",
        "LAnkleRoll",
    ],
    "right_leg": [
        "RHipYaw",
        "RHipRoll",
        "RHipPitch",
        "RKneePitch",
        "RAnklePitch",
        "RAnkleRoll",
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Canonical joint YAML (default: {DEFAULT_INPUT})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Where to write per-limb YAMLs (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated content differs from existing files.",
    )
    return parser.parse_args()


def load_joint_map(path: Path) -> dict[str, dict]:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    data = yaml.safe_load(path.read_text()) or {}
    joints = data.get("joints")
    if not isinstance(joints, list):
        raise ValueError(f"'joints' list missing in {path}")

    mapping: dict[str, dict] = {}
    for entry in joints:
        if not isinstance(entry, dict):
            continue
        name = entry.get("name")
        if not name:
            continue
        if name in mapping:
            raise ValueError(f"Duplicate joint entry for {name} in {path}")
        mapping[name] = entry
    return mapping


def make_header(source_path: Path) -> str:
    lines = [
        "# AUTO-GENERATED FILE — DO NOT EDIT",
        f"# Source: {source_path}",
        "# Generated by: hros5_utils/scripts/generate_joint_yamls.py",
        "# Edit the source file and re-run the generator.",
        "",
    ]
    return "\n".join(lines)


def render_group(names: list[str], joint_map: dict[str, dict], source_path: Path) -> str:
    missing = [name for name in names if name not in joint_map]
    if missing:
        raise ValueError(f"Missing joints in {source_path}: {', '.join(missing)}")

    joints_block: list[dict] = []
    for name in names:
        entry = joint_map[name]
        try:
            joint_id = entry["id"]
            cw_limit = entry["cw_limit"]
            ccw_limit = entry["ccw_limit"]
        except KeyError as exc:
            raise ValueError(f"Joint {name} missing required key {exc} in {source_path}")
        offset = float(entry.get("offset_deg", 0.0))
        joints_block.append(
            {
                "name": name,
                "id": joint_id,
                "cw_limit": cw_limit,
                "ccw_limit": ccw_limit,
                "offset_deg": offset,
            }
        )

    yaml_body = yaml.dump(
        {"joints": joints_block},
        Dumper=_IndentedDumper,
        sort_keys=False,
        default_flow_style=False,
        indent=2,
    )
    return make_header(source_path) + yaml_body


def ensure_all_assigned(joint_map: dict[str, dict]) -> None:
    expected = {name for group in JOINT_GROUPS.values() for name in group}
    extras = sorted(name for name in joint_map.keys() if name not in expected)
    if extras:
        raise ValueError(f"Joints not assigned to any group: {', '.join(extras)}")


def main() -> int:
    args = parse_args()
    joint_map = load_joint_map(args.input)
    ensure_all_assigned(joint_map)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    differences: list[Path] = []
    generated: list[Path] = []

    for group, names in JOINT_GROUPS.items():
        content = render_group(names, joint_map, args.input)
        output_path = args.output_dir / f"{group}.yaml"
        if args.check:
            if not output_path.exists() or output_path.read_text() != content:
                differences.append(output_path)
            continue
        output_path.write_text(content)
        generated.append(output_path)

    if args.check:
        if differences:
            print("Joint YAMLs are stale; re-run the generator:", file=sys.stderr)
            for path in differences:
                print(f"  {path}", file=sys.stderr)
            return 1
        print("Joint YAMLs are up to date.")
        return 0

    if generated:
        print("Generated joint YAMLs:")
        for path in generated:
            print(f"  {path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
