#!/usr/bin/env bash
set -e

# Usage:
#   ./scripts/update_master_issue.sh          # defaults to issue #1
#   ./scripts/update_master_issue.sh 5        # use issue #5 as master

MASTER_ISSUE_NUM="${1:-1}"

REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)

PHASES=("P0" "P1" "P2" "P3" "P4" "P5" "P6")

PHASE_LINES=()

# Collect phase parent issues (by label phase-Px)
for PHASE in "${PHASES[@]}"; do
  ISSUE_JSON=$(gh issue list \
    --label "phase-$PHASE" \
    --state all \
    --json number,title \
    --jq '.[0]' 2>/dev/null || true)

  if [ -z "$ISSUE_JSON" ] || [ "$ISSUE_JSON" = "null" ]; then
    echo "Warning: no parent issue found with label phase-$PHASE, skipping..."
    continue
  fi

  NUM=$(echo "$ISSUE_JSON"   | jq -r '.number')
  TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')

  PHASE_LINES+=("- [ ] #${NUM} **${TITLE}**")
done

TMP_BODY=$(mktemp)

{
  printf '%s\n' '# HR-OS5 Roadmap Master Issue (P0–P6)'
  printf '\n'
  printf '%s\n' 'This issue is the **top-level roadmap** for the HR-OS5 humanoid project.'
  printf '\n'
  printf '%s\n' 'It links to:'
  printf '\n'
  printf '%s\n' '- 7 **phase parent issues** (P0–P6), each representing a major phase'
  printf '%s\n' '- All **sub-issues**, which are assigned to phases via labels and milestones'
  printf '\n'
  printf '%s\n' 'Use:'
  printf '\n'
  printf '%s\n' '- **This issue** to see the whole journey'
  printf '%s\n' '- **Phase parents** to see progress inside each phase'
  printf '%s\n' '- **Milestones** and **labels** to filter and slice work'
  printf '\n'
  printf '%s\n' '---'
  printf '\n'
  printf '%s\n' '## Phase Overview'
  printf '\n'
  printf '%s\n' 'Each phase has:'
  printf '\n'
  printf '%s\n' '- A parent issue: `[P*] HR-OS5 Phase * – ...`'
  printf '%s\n' '- A milestone: `P* – <name>`'
  printf '%s\n' '- A set of child issues with label `P*`'
  printf '%s\n' '- An autogenerated checklist in the phase parent linking all sub-issues'
  printf '\n'
  printf '%s\n' '### Phase Parents'
  printf '\n'

  # phase parent checklist
  for line in "${PHASE_LINES[@]}"; do
    printf '%s\n' "$line"
  done

  printf '\n'
  printf '%s\n' 'When a phase is “functionally done”, tick its line here.'
  printf '\n'
  printf '%s\n' '---'
  printf '\n'
  printf '%s\n' '## How Issue Tracking is Structured'
  printf '\n'
  printf '%s\n' '### 1. Labels'
  printf '\n'
  printf '%s\n' '- `hr-os5` – all roadmap issues'
  printf '%s\n' '- `phase-P0` … `phase-P6` – marks the **phase parent issue**'
  printf '%s\n' '- `P0` … `P6` – marks all issues belonging to that phase'
  printf '%s\n' '- Package labels:'
  printf '%s\n' '  - `hros5_description`'
  printf '%s\n' '  - `hros5_control`'
  printf '%s\n' '  - `hros5_dynamixel_bridge`'
  printf '%s\n' '  - `hros5_teleop`'
  printf '%s\n' '  - `hros5_head_tracker_cpp`'
  printf '%s\n' '  - `hros5_utils`'
  printf '%s\n' '  - `hros5_perception`'
  printf '%s\n' '  - `hros5_gazebo`'
  printf '%s\n' '  - `hros5_moveit_config`'
  printf '%s\n' '  - `hros5_behaviors`'
  printf '%s\n' '  - `hros5_bringup`'
  printf '\n'
  printf '%s\n' 'Use:'
  printf '%s\n' '- `P?` to filter by phase'
  printf '%s\n' '- `hros5_*` to filter by package'
  printf '\n'
  printf '%s\n' '### 2. Milestones'
  printf '\n'
  printf '%s\n' 'Each phase has a matching milestone:'
  printf '\n'
  printf '%s\n' '- `P0 – Foundation`'
  printf '%s\n' '- `P1 – Teleop`'
  printf '%s\n' '- `P2 – Digital twin`'
  printf '%s\n' '- `P3 – IK`'
  printf '%s\n' '- `P4 – Balance`'
  printf '%s\n' '- `P5 – Walking`'
  printf '%s\n' '- `P6 – Autonomous demo`'
  printf '\n'
  printf '%s\n' 'All phase parents and sub-issues in that phase are assigned to the same milestone.'
  printf '\n'
  printf '%s\n' '### 3. Phase Parent Issues & Sub-Issue Checklists'
  printf '\n'
  printf '%s\n' 'Each phase parent issue:'
  printf '\n'
  printf '%s\n' '- Has labels: `hr-os5`, `phase-Px`, and `Px`'
  printf '%s\n' '- Is assigned to the corresponding milestone'
  printf '%s\n' '- Contains a `## Tasks` section with a checklist like:'
  printf '\n'
  printf '%s\n' '```markdown'
  printf '%s\n' '## Tasks'
  printf '\n'
  printf '%s\n' '- [ ] #12 [P0] hros5_description: verify hros5.xacro as top-level'
  printf '%s\n' '- [ ] #13 [P0] hros5_description: cleanup component xacros'
  printf '%s\n' '- [ ] #14 [P0] hros5_description: add missing mesh and collision geometry'
  printf '%s\n' '...'
  printf '%s\n' '```'
  printf '\n'
  printf '%s\n' 'GitHub automatically:'
  printf '\n'
  printf '%s\n' '- Turns `#12` into a link to that issue'
  printf '%s\n' '- Checks the box when a child issue is closed'
  printf '%s\n' '- Shows a progress bar at the top of the parent issue'
  printf '\n'
  printf '%s\n' '---'
  printf '\n'
  printf '%s\n' '## How to Add New Work'
  printf '\n'
  printf '%s\n' '### Adding a new task'
  printf '\n'
  printf '%s\n' '1. Create a new issue with a title like:'
  printf '%s\n' '   - `[P?] <package>: <short description>`'
  printf '%s\n' '2. Add labels:'
  printf '%s\n' '   - `hr-os5`'
  printf '%s\n' '   - `P?` (phase)'
  printf '%s\n' '   - `hros5_<package>`'
  printf '%s\n' '3. Assign the correct milestone:'
  printf '%s\n' '   - `P? – <phase name>`'
  printf '%s\n' '4. (Optional) Re-run the checklist update script to pull it into the phase parent’s `## Tasks` section.'
  printf '\n'
  printf '%s\n' '### Changing a task’s phase'
  printf '\n'
  printf '%s\n' '- Update the `P?` label and the milestone.'
  printf '%s\n' '- Re-run the checklist update script so it appears under the correct parent.'
  printf '\n'
  printf '%s\n' '---'
  printf '\n'
  printf '%s\n' '## Local Scripts'
  printf '\n'
  printf '%s\n' 'These helper scripts live under `scripts/` and keep GitHub tracking in sync:'
  printf '\n'
  printf '%s\n' '- `fix_phase_parents.sh`  '
  printf '%s\n' '  Ensures phase parent issues have the correct `P?` label and milestone.'
  printf '\n'
  printf '%s\n' '- `assign_milestones.sh`  '
  printf '%s\n' '  Assigns milestones to all issues based on `P0..P6` labels.'
  printf '\n'
  printf '%s\n' '- `update_phase_checklists.sh`  '
  printf '%s\n' '  Regenerates the `## Tasks` checklist in each phase parent based on `P?` labels.'
  printf '\n'
  printf '%s\n' '- `update_master_issue.sh`  '
  printf '%s\n' '  Regenerates this master issue body with links to all phase parents.'
  printf '\n'
  printf '%s\n' 'You can re-run them at any time to resync tracking.'
  printf '\n'
  printf '%s\n' '---'
  printf '\n'
  printf '%s\n' '## Status Notes'
  printf '\n'
  printf '%s\n' 'Use this section for high-level notes about where the project is:'
  printf '\n'
  printf '%s\n' '- Current focus: `P? – ...`'
  printf '%s\n' '- Next big milestone:'
  printf '%s\n' '- Risks / blockers:'
  printf '%s\n' '- Notes:'
} > "$TMP_BODY"

echo "Updating master issue #$MASTER_ISSUE_NUM in $REPO..."
gh issue edit "$MASTER_ISSUE_NUM" --body-file "$TMP_BODY"

rm -f "$TMP_BODY"

echo "Done. Open issue #$MASTER_ISSUE_NUM to see the updated master roadmap."
